name: 'saude_rj'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'saude_rj'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  saude_rj:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
      +schema: staging
    
    # Config indicated by + and applies to all files under models/core/
    core:
      +materialized: table
      +schema: core
      
    # Config indicated by + and applies to all files under models/marts/
    marts:
      +materialized: table
      +schema: marts

# Documentation
docs-paths: ["docs"]

# Variables
vars:
  # BigQuery datasets
  raw_dataset: 'brutos_saude'
  
  # Date filters
  start_date: '2024-01-01'
  
  # Data quality thresholds
  min_records_threshold: 10